### ISSUE TITLE
"strapi4-ftp-provider" doesn't implement the uploadStream function

### ISSUE THREAD

**Issue by asijoumi** [BaptisteAg/strapi-provider-ftp#1]
Hi !

I installed the strapi4-ftp-provider package. But when I start strapi, I got this warning : 

`Warning: The upload provider "strapi4-ftp-provider" doesn't implement the uploadStream function. Strapi will fallback on the upload method. Some performance issues may occur.`

When I try to upload a media, I got this error : 

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
FTPError: 553 Can't open that file: No such file or directory
    at FTPContext._onControlSocketData (/strapi-project/node_modules/basic-ftp/dist/FtpContext.js:283:39)
    at Socket.<anonymous> (/strapi-project/node_modules/basic-ftp/dist/FtpContext.js:127:44)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
```

Do you know what happened and how to fix it ?

Thanks,
Aimen

**Comment by asijoumi** [comment]
This is only warning

**Comment by patodoldan** [comment]
Im having the same warning. When I try to upload a logo for the Strapi panel I get an error. How could I fix this?
